---
sudo: required
language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
dist: xenial
services:
  - docker
before_install:
  - sudo apt-get -qq update
install:
  - pip install 'molecule[docker]'
script:
  - cd ../..
  - mv $TRAVIS_BUILD_DIR computerlyrik.bitbucket_backup
  - cd computerlyrik.bitbucket_backup
  - molecule test
