---
# Initialize bare repo first to not have the password written in the config file
- name: "create bare repository for {{ repo_name }}"
  command: "git init --bare {{ repo_dir }}"
  args:
    creates: "{{ repo_dir }}/HEAD"

- name: set clone url
  set_fact:
    clone_url: "{{ clone_url.split('@')[0] }}:{{ bitbucket_backup__app_password }}@{{ clone_url.split('@')[1] }}"
  when: bitbucket_backup__auth_enabled

# https://github.com/ansible/ansible-lint/issues/490
- name: "fetch bitbucket repository {{ repo_name }}"
  command: "git -C {{ repo_dir }} fetch --force --prune {{ clone_url }} refs/heads/*:refs/heads/* refs/tags/*:refs/tags/*"
  register: git_fetch
  changed_when: git_fetch.stdout | length > 0
