---
dependency:
  name: galaxy
driver:
  name: docker
lint:
  name: yamllint
platforms:
  - name: instance
    image: ubuntu:18.04
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
provisioner:
  name: ansible
  lint:
    name: ansible-lint

# https://github.com/ansible/molecule/issues/1727
# https://github.com/philpep/testinfra/pull/410
# verifier:
#  name: testinfra
#  lint:
#    name: flake8
